import { NextPage } from "next"
import Head from "next/head"

const Dashboard: NextPage = () => {

    return (
        <>
            <Head>
                <title>UCar</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

            </main>
        </>
    )
}

export default Dashboard
